### ISSUE TITLE
Allow way of partitioning nodes into different sections

### ISSUE THREAD

**Issue by JonnySpruce** [JonnySpruce/striot-gui#7]
Currently there are a few different ways to achieve this:

1. Use the ''Sub-flow" option on Node-RED:
![subflows](https://user-images.githubusercontent.com/30812276/76701228-46237a80-66b7-11ea-8f44-a7185be83ba2.gif)
    - This seems fairly intuitive, but would need to handle cases where some nodes are not in a subflow *(may not be a huge issue, since all nodes are given a `z` property, which is unique to the sub-flow, and no sub flow is effectively treated as another sub-flow)*
    - The connections between nodes at the edges of sub-flows are a little more complex, so this would require additional processing in the code
    - This is probably the most intuitive option
1. Add a `partition` property to each node, which the user has to define which partition the node is in
    - Relies on the user having correct ordering of partitions and nodes (e.g. probably couldn't have nodes in structure `1 -> 2 -> 1` partitions ids) 
    - Has same issue as above - what to do if node not defined as in partition?
    - Makes it difficult for the user to reorder nodes
    - Easiest to implement in code

**Comment by jmtd** [comment]
The ultimate aim for Striot is for the user not to supply a manual partition map, as now, but instead describe the available partitions via a *catalogue* and determine the best partitioning for the available environment. So I would suggest not sweating about this one too much!

**Comment by JonnySpruce** [comment]
@jmtd Great, then for now would an acceptable solution be to have two partitions with the main nodes in the first and only the sink in the second partition?

**Comment by jmtd** [comment]
Yes that sounds like a good idea!

**Comment by JonnySpruce** [comment]
@jmtd - do the order of the elements in a single partition matter? I.e. is there a difference between `[[1,2,3],[4]]` and `[[3,2,1],[4]]`?

**Comment by jmtd** [comment]
> @jmtd - do the order of the elements in a single partition matter? I.e. is there a difference between [[1,2,3],[4]] and [[3,2,1],[4]]?

No I don't think so.
