### ISSUE TITLE
Make Main.hs execute StrIoT

### ISSUE THREAD

**Issue by JonnySpruce** [JonnySpruce/striot-gui#8]
This will allow for a user to simply pass a Node-RED json file to the `striot-gui-exe` executable, and have StrIoT generate the relevant files as a result. There are a number of work items which need to be done to achieve this:

- [x] [Add configuration node](https://github.com/JonnySpruce/striot-gui/issues/6)
- [ ] Figure out a way to handle partitioning (https://github.com/JonnySpruce/striot-gui/issues/7) OR as a first step - add code to create a single partition containing all nodes first.

**Comment by JonnySpruce** [comment]
I have tried to hard code a test version of this, with unfortunately limited results.

using the following code:
```haskell
-- Main.hs
module Main where

import           System.Environment

import           NRNode
import           ToStreamGraph
import           Striot.CompileIoT
import           Striot.StreamGraph


opts :: GenerateOpts
opts = GenerateOpts
  { imports   = [ "Striot.FunctionalIoTtypes"
                , "Striot.FunctionalProcessing"
                , "Striot.Nodes"
                , "Control.Concurrent"
                , "System.Random"
                ]
  , packages  = ["random"]
  , preSource = Nothing
  , rewrite   = False
  }

main :: IO ()
main = do
  args <- getArgs
  case args of
    [fileName] -> do
      x <- nodesFromJSON fileName
      let striotNodes = toStreamGraph x
      print striotNodes
      partitionGraph striotNodes [[1, 2, 3]] opts
    _ -> helpText

helpText :: IO ()
helpText = putStrLn "Usage: haskell-gui /path/to/node-red/export"
```
and the following nodes defined (irrelevant properties removed): 
```json
[{
    "id": "53d73312.aa3aec",
    "type": "generic-input",
    "func": "do\n    threadDelay (1000*1000)\n    return \"Hello World!\"",
    "output": "String",
    "wires": [
        ["e2841e3f.0d379"]
    ]
}, {
    "id": "e2841e3f.0d379",
    "type": "filter",
    "func": "(\\i -> (read i :: Int) > 5)",
    "output": "String",
    "wires": [
        ["fad96b10.65b4a8"]
    ]
}, {
    "id": "fad96b10.65b4a8",
    "type": "filter",
    "func": "(\\i -> (read i :: Int) < 8)",
    "output": "String",
    "wires": [
        []
    ]
}]
```
When running `striot-gui-exe` and passing in the path to the above JSON file, I get a correctly output StreamGraph:
```haskell
Overlay (Connect (Vertex (StreamVertex {vertexId = 1, operator = streamSource, parameters = ["do\n    threadDelay (1000*1000)\n    return \"Hello World!\""], intype = "String", outtype = "String"})) (Vertex (StreamVertex {vertexId = 2, operator = streamFilter, parameters = ["(\\i -> (read i :: Int) > 5)","s"], intype = "String", outtype = "String"}))) (Overlay (Connect (Vertex (StreamVertex {vertexId = 2, operator = streamFilter, parameters = ["(\\i -> (read i :: Int) > 5)","s"], intype = "String", outtype = "String"})) (Vertex (StreamVertex {vertexId = 3, operator = streamFilter, parameters = ["(\\i -> (read i :: Int) < 8)","s"], intype = "String", outtype = "String"}))) Empty)
```
And an error/warning:
`striot-gui-exe: Prelude.head: empty list`

When I look at the files created, I have a correctly created `Dockerfile`, and an empty `node.hs` file.
I'm not sure exactly why there's an issue here. The error is definitely created during the line:
```haskell
partitionGraph striotNodes [[1, 2, 3]] opts
```
As commenting it out stops it being printed.

@adam-cattermole, @jmtd - any ideas why?

**Comment by adam-cattermole** [comment]
I think Jon might have a better idea of what is going wrong here, but from a brief look I suspect it might be that we assume that all valid partitionings include a `sink`. The `source`, `link` and `sink` types must also be on separate nodes, so I'd expect a working definition to look something like this:

```Haskell
partitionGraph striotNodes [[1, 2, 3], [4]] opts
```

Where operation 4 is of type `Sink`.

Jon, is this right or am I making this up? Taking our filter example and removing the last two operators (`window` and `sink`) from `generate.hs` gives the same empty list error.

**Comment by JonnySpruce** [comment]
Thanks @adam-cattermole, that definitely makes sense. I've added the Sink node type now (https://github.com/JonnySpruce/striot-nodes/pull/2), will try again and see if that solves it.

**Comment by JonnySpruce** [comment]
@adam-cattermole I can confirm that has solved the issue, thanks!

**Comment by adam-cattermole** [comment]
Awesome, glad I could help!

**Comment by jmtd** [comment]
Yep good catch @adam-cattermole — you have hit https://github.com/striot/striot/issues/27.
